typography_spectrum: 0.38479
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: Stories
  appId: '844076975693316'
layout_spectrum: 0.99931
analytics:
  google: UA-33184121-1
  facebook: null
  twitter: null
author:
  name: Adrian Wedd
  email: adrian@adrianwedd.com
  url: 'http://adrianwedd.com'
name: adrian wedd
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Contact
    url: 'http://adrian.wedd.co/contact-adrian-wedd/'
    type: external
  - name: Social
    url: 'http://adrian.wedd.co/social/'
    type: external
favicon: null
title: adrianwedd.com | Adrian Wedd
description: adrian at adrian wedd dot com
purpose:
  - name: null
    item: null
    url: null
