name: Adrian Wedd
layout_spectrum: 0.09077577409334481
typography_spectrum: 0.6880759228952229
cta: {}
analytics:
  google: UA-33184121-1
opengraph:
  type: Stories
  appId: '844076975693316'
color:
  brandColors:
    - '#FAE7CF'
    - '#2F0000'
    - '#73C6C9'
    - '#CD984D'
    - '#9562A4'
  brandStrength: 0.8292580789420754
  lightness: 0.6416246867738664
  saturation: 0.5794318364933133
  rhythmicContrast: 0.1551246428862214
purpose:
  - type: contact
    label: Call
    url: 'tel:+61407081084'
  - type: contact
    label: Email
    url: 'mailto:adrian@adrianwedd.com'
title: Adrian Wedd | adrianwedd.com
description: adrian at adrian wedd dot com
author:
  name: Adrian Wedd
  url: 'http://adrianwedd.com'
  email: adrian@adrianwedd.com
content_rating:
  adult: false
navigation:
  - name: Digital Agency
    url: 'http://d1g1tal.agency'
    type: external
  - name: Facebook
    url: 'https://facebook.com/adrianwedd'
    type: external
  - name: Google+
    url: 'https://plus.google.com/+adrianwedd'
    type: external
  - name: LinkedIn
    url: 'https://www.linkedin.com/in/adrianwedd'
    type: external
  - name: Twitter
    url: 'https://twitter.com/adrianwedd'
    type: external
content: []
github: true
