typography_spectrum: 0.002011460717767477
color:
  brandColors:
    - '#FAE7CF'
    - '#2F0000'
    - '#73C6C9'
    - '#CD984D'
    - '#9562A4'
  brandStrength: 0.27151853288523853
  lightness: 0.4140655789524317
  saturation: 0.6215793108567595
  rhythmicContrast: 0.962816528743133
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8408321919851005
analytics:
  google: UA-33184121-1
  facebook: null
  twitter: null
author:
  name: Adrian Wedd
  email: adrian@adrianwedd.com
  url: 'http://adrianwedd.com'
name: adrian wedd
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: adrianwedd.com | Adrian Wedd
description: adrian at adrian wedd dot com
purpose:
  - name: null
    item: null
    url: null
