name: adrian wedd
favicon: null
layout_spectrum: 0.99931
typography_spectrum: 0.38479
title: 'adrianwedd.com | Adrian Wedd'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-33184121-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 0.75
purpose:
  - name: null
    item: null
    url: null
